FROM resin/%%RESIN_MACHINE_NAME%%-openjdk

RUN apt-get update && \
    apt-get install -y git bluez build-essential cmake

RUN git clone https://github.com/intel-iot-devkit/tinyb.git && \
    cd tinyb && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install
